### ISSUE TITLE
Provide a tool to upgrade the Apex Trigger API versions

### ISSUE THREAD

**Issue by dicksonstephen** [SFDO-Community/declarative-lookup-rollup-summaries#1188] opened 2022-04-28 13:33 UTC
I'm just cross-posing this issue that was originally raised on the Trailhead community and discussed in Slack.

https://trailhead.salesforce.com/trailblazer-community/feed/0D54S00000Gzu2lSAB

**Is your feature request related to a problem? Please describe.**
Posted on the DLRS Trailhead community:
Hi, I recently updated the DLRS package from an older version to version 2.14 (I wasn't able to upgrade to the most recent version 2.15 due to an error). Through Salesforce Optimizer I see some of our org's old DLRS-related Apex classes and triggers are on old API versions, going back to API version 42.

From the [DLRS release notes it looks the 2.14 package I'm on now should be using API version 51.0](https://github.com/SFDO-Community/declarative-lookup-rollup-summaries), but updating the package didn't update API versions on existing DLRS-related Apex in our org. It looks like the API version 51.0 might only apply for newly created triggers/classes if I were to create a rollup on an object without existing DLRS rollups. I'm wondering if manually updating the API version to 51.0 on our existing DLRS Apex classes and triggers will cause issues with the package. Does anyone have experience with this issue?

**Describe the solution you'd like**
Anthony Heber's ultimate response:
Great, I talked about this with some others and I think we'll look at how to get DLRS to do this for you eventually. The good news is this should not really cause problems but I'm a lot like you, I really like making the Optimizer happy and knowing that I'm doing my part to keep things cleaned up.

**Comment by aheber** [comment] 2024-05-23 15:41
Duplicate of #674

**Closed by aheber** 2024-05-23 15:41 UTC
Labels: enhancement, Dev Team
