### ISSUE TITLE
Allow for more characters in SOQL query

### ISSUE THREAD

**Issue by MelanieTolomeo** [SFDO-Community/declarative-lookup-rollup-summaries#1296] opened 2023-02-01 20:32 UTC
**Is your feature request related to a problem? Please describe.**
When I create a DLRS, the SOQL query field has a limited # of characters so does not allow for complex logic. This is especially challenging when there are long API names of fields.

**Describe the solution you'd like**
Longer text field. Maybe even option to create & then reference an Apex Class that includes the SOQL query in order to create repeatable code.

**Describe alternatives you've considered**
People use the workaround of a formula checkbox "include in DLRS"

**Additional context**
Will give ability to add more complex logic

**Comment by aheber** [comment] 2024-05-22 16:52
Duplicate of #302

**Closed by aheber** 2024-05-22 16:52 UTC
Labels: enhancement
