### ISSUE TITLE
AllOrNone flag in DLRS

### ISSUE THREAD

**Issue by mdemeglio** [SFDO-Community/declarative-lookup-rollup-summaries#301] opened 2016-02-17 14:53 UTC
When DLRS updates the parent record in a rollup, is there a way to specify the AllOrNone flag for the DML operation? We have a batch of records that are failing on insert because one parent-level record is being updated and fails a validation rule. We'd like for AllOrNone to be False so the passing records can still be updated by DLRS.

**Comment by afawcett** [comment] 2016-02-18 17:54
I think this has been raised before, not sure if it has a GitHub issue though, so i'll leave this one and if i find a duplicate will close one. Meanwhile, its for sure been asked for before and is a valid enhancement. Marking as such.

**Comment by aheber** [comment] 2023-03-08 22:32
Duplicate of #287, gives us a possible way to handle this error condition rather than failing outright, if we can allow for the parent's to fall out of sync with the correct rollup value.

**Closed by aheber** 2023-03-08 22:32 UTC
Labels: enhancement, Dans List
