### ISSUE TITLE
DLRS Record Deleted - Still Referenced in Apex Class

### ISSUE THREAD

**Issue by mrthompsonplease** [SFDO-Community/declarative-lookup-rollup-summaries#891] opened 2019-12-26 21:58 UTC
hi - i deleted a roll up record, but it seems to still be referencing the criteria of the roll-up record in the related apex class. I deleted the roll-up record, removed it from the recycle bin, deleted and reployed the trigger, but it doesnt seem to fix anything. What gives? What could i be missing?

**Comment by afawcett** [comment] 2019-12-28 01:32
I'm not 100% sure what your issue is here from this description. But I am going to guess its the apex trigger "Apex Class" your referring to? In this case use the "Manage Child Trigger" button and at the bottom of the page that comes up click "Remove". This will undeploy the Apex Trigger associated with the rollup. Note if you have other rollups using the child object, that you want to keep you still need this apex trigger.

**Comment by vanillabasic** [comment] 2020-01-03 14:53
Yeah that didn't work either. I tried removing as you pointed out and then redeploying but the the code still seems to be referencing the criteria of the old dlrs record. It's specifically calling out the name of the old DLRS record even though it was deactivated, deleted and removed from the recycle bin.

**Comment by afawcett** [comment] 2020-04-06 05:52
@vanillabasic sorry but i am unclear what you problem is now, can you include some screenshots and steps you are following to reproduce the issue?

**Comment by mdoappway** [comment] 2020-04-08 10:56
@vanillabasic  could your case be related/similar to this other one? 
https://github.com/afawcett/declarative-lookup-rollup-summaries/issues/928

**Comment by aheber** [comment] 2023-03-15 16:27
I'm going to close this. If further assistance is needed please reach out to the Trailblazer Community Group for further assistance. We are trying to keep support requests with that group as there is a much broader collection of individuals available to help and much more varied experiences.

**Closed by aheber** 2023-03-15 16:27 UTC
Labels: discussion
