### ISSUE TITLE
Trigger not properly working on delete

### ISSUE THREAD

**Issue by mdoappway** [SFDO-Community/declarative-lookup-rollup-summaries#928] opened 2020-04-06 14:58 UTC
The Lookup Rollup Summary works well on insert and update, although when deleting a record the after delete still takes into consideration the deleted records when calculating the total value of a rollup. And this generates various issues.

In my opinion the selectActiveByChildObject()  or similar function should avoid the objects in Trigger.Old ids when Trigger.isDelete.

So basically to do something like:
List<SObject> childRecords = Trigger.isDelete ? Trigger.old : Trigger.new;
--
get the childRecordsIds ids from childRecords 

and 
ff  Trigger.isDelete then SOQL query append " AND childObjectIds not in :childRecordsIds "

I hope this makes sense

**Comment by afawcett** [comment] 2020-04-06 21:41
@mdoappway can you please help me better understand the scenario here. Please describe and example rollup, the steps the user performances and how the current behavior is not expected. Then I think it will be easier to understand your code change suggestion. Thank you, much appreciated.

**Comment by mdoappway** [comment] 2020-04-07 08:02
Let's say you have a SUM() rollup summary of childs on a parent.

Child 1 created: The rollup sums child1 .
Child 2 created: The rollup sums child1 + child2.
Child 3 created: The rollup sums child1 + child2 + child3.
The rollup works perfectly when you create one child after another. Good!
Delete child 2: the trigger on after delete runs > it collects all the children, being child1, child2 AND child3, which from a business standpoint is deleted, thus not to be counted anymore in the sum. WRONG

Of course the next create/update operation will re-fix the to correct sum, but since then the sum value is inconsistent 

Does it make sense so far?
I'll add a  custom trigger that we have put in place to highlight the solution we have put in place. Line 2 and line 19 should be self explicable

[UpdateProjectTimecardTotalValues.txt](https://github.com/afawcett/declarative-lookup-rollup-summaries/files/4442735/UpdateProjectTimecardTotalValues.txt)

**Comment by afawcett** [comment] 2020-04-07 19:51
Hi, sorry I am confused. Are you even using DLRS? Your sample code is doing rollups in code right? Also, if you are using DLRS, how are you actually defining the rolls to do the bubbling up of the children the way you describe?

**Comment by mdoappway** [comment] 2020-04-07 20:48
Hi Andrew, let's do a step back. We used the DLRS. Everything was working as expected and we are still using it in many other cases. 
Although we noted the misbehavior I've described in my previous comment. That is, the one not properly excluding a deleted object from the rollup when in the after delete.

To avoid the mistake we have moved from the DLRS to another custom solution (for which I've reported our new trigger just as an example of how the code should exclude "deleted" objects from the rollups). 
With the new solution the mistake is in fact avoided. 

That's why I recommend to take into account a similar approach in your code, because it seems affected by the mistake I've reported before.

I hope it makes more sense now. BTW it is a pleasure to have an active conversation here and in case we can set up a call to better explain the topic.

**Comment by afawcett** [comment] 2020-04-08 02:22
So I created my go to rollup to test this myself

**Steps to Test:**
- I created an Account
- I created an associated Opportunity value $100
- I created an associated Opportunity value $200
- Account Annual Revenue was correctly updated to $300.
- I deleted the second Opportunity 
- Account Annual Revenue was correctly updated to $100 (it requires remaining children)

**Rollup Used**
![image](https://user-images.githubusercontent.com/1167760/78737735-1c035800-7905-11ea-8ebc-b60a77c91435.png)

**Comment by afawcett** [comment] 2020-04-08 02:23
One thing that is a bit funky sometimes in Lightning Experience is the field values updated in Apex Triggers are not always reflected in the UI. You either have to refresh the page, or navigate to another record or fake edit a record. Could it be this field caching issue gave you the impression delete was not working?

**Comment by mdoappway** [comment] 2020-04-08 10:53
Hi Andrew, first of all again thanks for your presence and support ! 
I've tried a simple use case (opportunity & child_opportunities) and it worked well as expected when deleting objects.
I've then tested with sum milestone values and it also worked properly even when deleting them.
Confused by it, I finally re-tested the similar use case everything started from and I was able to reproduce the issue.

I'm attaching here the sequence of actions happening between "timecards and project" objects.

DLRS version in use it 2.11.1 as also included in the printscreens.

[reproduced_use_case.zip](https://github.com/afawcett/declarative-lookup-rollup-summaries/files/4449998/reproduced_use_case.zip)

I hope this might come in handy

**Comment by afawcett** [comment] 2020-04-08 16:20
Yeah that looks odd. Can you run a debug log for action when you delete the time card. Even though most of the code in the DLRS package is hidden in the debug log (by design) you still get to see SOQL's that run and can tell you if DLRS is even trying to query for the lookup to run and also how often. Also do you have any other DLRS rollups on these objects?

**Comment by ashwinjangam** [comment] 2020-04-10 19:30
Hello Andrew, 
I am getting ApexAsync Limit issue due to dlrs.RollupCalculateJob and the entryPoint count 230771. How could I solve this issue. Please guide me.
Thanks

**Comment by afawcett** [comment] 2020-04-16 06:46
@ashwinjangam this is not the appropirte issue to raise your issue on. Please raise a new one. Meanwhile though you should review all the other async jobs your org is using. This is a shared limit accross all code in your org. See Setup > Apex Scheduled Jobs.

**Comment by mwhenry** [comment] 2020-11-22 22:04
@afawcett @mdoappway I encountered a similar issue where deleted records continued to be included in the DLRS results. My operation was to pull a value from the most recent child record and put it on the parent. But when deleting the most recent record, the parent would not update. 

What I discovered was that there was a field I could not see in Setup (but was able to discover using Salesforce Inspector) called "IsDeleted". When I added the Relationship Criteria "IsDeleted = false" to the DLRS, it worked as intended. For context, I was working with a custom object provided in a managed package.

Thought you (and anyone else with a similar issue) might find this of interest.

BTW @afawcett thanks for this amazing tool!

**Comment by jas-rubin** [comment] 2021-03-01 17:46
@mwhenry This solved my similar issue.  Thanks

**Comment by umeditor** [comment] 2021-06-16 13:41
I believe we are seeing a similar issue: a sum rollup is not calculating the correct value when records are deleted. Manually running the DLRS generates the correct value.

**Comment by umeditor** [comment] 2021-06-16 14:41
What can I provide to help explore this issue? I'm happy to setup a test environment with an example if necessary.

**Comment by BluviumDhiren** [comment] 2021-08-05 05:12
@afawcett : I have installed the DLRS package in my salesforce sandbox org. Everything is working fine except for one. whenever I am trying to merge two duplicate account records it throws me a error as "**Apex trigger dlrs_AccountTrigger caused an unexpected exception, contact your administrator: dlrs_AccountTrigger: execution of AfterDelete caused by: dlrs.RollupService.RollupValidationException: Scheduled rollups are running in legacy mode and are unable to resolve corresponding shadow rollups. Please visit the Lookup Rollup Summary Tools tab for more information and steps to resolve.: (dlrs)**".  I am trying to debug it, but unable to find out anything from debug logs, where in its goes into after delete event as 
"dlrs_AccountTrigger on Account trigger event AfterDelete|__sfdc_trigger/dlrs_AccountTrigger" and then it throws the below error 
"Class.dlrs.RollupService: line 1082, column 1
Class.dlrs.RollupService: line 1001, column 1
Class.dlrs.RollupService.triggerHandler: line 329, column 1
Trigger.dlrs_AccountTrigger: line 7, column 1
23:48:22.300 (963708661)|FATAL_ERROR|dlrs.RollupService.RollupValidationException: Scheduled rollups are running in legacy mode and are unable to resolve corresponding shadow rollups. Please visit the Lookup Rollup Summary Tools tab for more information and steps to resolve. "

Can you please help me to understand why and from where I am facing this issue.  Appreciate your help. 
Thanks,
Dhirendra

**Comment by ayenione** [comment] 2021-10-30 16:12
> @afawcett @mdoappway I encountered a similar issue where deleted records continued to be included in the DLRS results. My operation was to pull a value from the most recent child record and put it on the parent. But when deleting the most recent record, the parent would not update.
> 
> What I discovered was that there was a field I could not see in Setup (but was able to discover using Salesforce Inspector) called "IsDeleted". When I added the Relationship Criteria "IsDeleted = false" to the DLRS, it worked as intended. For context, I was working with a custom object provided in a managed package.
> 
> Thought you (and anyone else with a similar issue) might find this of interest.
> 
> BTW @afawcett thanks for this amazing tool!

This works for me - just used the IsDeleted = FALSE as a criteria and then got the rollup field to update after a record is deleted - trying to count the number of related accounts on a contact. Thanks

**Comment by AccosysLLC** [comment] 2022-01-01 01:33
I ran into this problem myself rolling up a custom field from the Payment object to Opportunities (in NPSP) and had the issue wherein deleted records were still getting included. 

This isn't a bug in my case but rather info for others searching - if you have Aggregate All Rows checked in your DLRS rule, it will include records in the Recycle Bin (Deleted). Unchecking Aggregate All Rows solved my problem.

Again, not a bug, just an FYI for others that like me didn't know exactlt what Aggregate All Rows causes.

**Comment by aheber** [comment] 2023-03-15 16:54
I'm going to mark this as closed. I think there is enough detail here to help anyone that has this issue going forward.

**Closed by aheber** 2023-03-15 16:54 UTC
Labels: discussion
