### ISSUE TITLE
dlrs__LookupRollupSummaryScheduleItems__c are being created for "Calculation Mode = Realtime" DLRS's on Account.

### ISSUE THREAD

**Issue by lrock-eqt** [SFDO-Community/declarative-lookup-rollup-summaries#1479] opened 2024-07-03 19:05 UTC
**Describe the bug**
We have 5 DLRS rollups with a Calculation Mode of "Realtime" that are generating dlrs__LookupRollupSummaryScheduleItems__c records for some reason.

The dlrs__LookupRollupSummaryScheduleItems__c records in question were all created today. None of the affected DLRS configurations were last updated more recently than a week ago. All of them have a calculation mode of "Realtime" and a "Parent Object" of Account, but have differing Child Objects. The triggers are all generated and do not have any additions/changes.

**To Reproduce**
Note: We were unable to replicate this behavior in a full sandbox environment, and are unsure why this occurring on some but not other rollups.
1. Update a child record of Account to trigger one of the 5 affected DLRS calculations.
2. Query the dlrs__LookupRollupSummaryScheduleItems__c table and observe that a schedule item was incorrectly created, and is related to one of the 5 affected DLRS configurations.
Note: the Account is still updated in real time.

**Expected behavior**
No dlrs__LookupRollupSummaryScheduleItems__c should be generated when the Calculation Mode is "Realtime"

**Screenshots**
![LookupRollupIssue](https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/assets/103588445/93ab1d26-99a6-4114-8da6-261be7ff0fae)

**Comment by aheber** [comment] 2024-07-03 20:29
This sounds like a duplicate of #1300, please review my notes at the end of that issue as to where the code might create scheduled items as a result of record merging.

**Closed by aheber** 2024-07-03 20:29 UTC
Labels: bug

**Comment by lrock-eqt** [comment] 2024-07-08 13:59
@aheber Ah, so it's currently undocumented. I had heard that merging might be an issue but I couldn't find any evidence of that in the official docs, thanks for the confirmation. I double checked and all of the accounts related to scheduled items were merged, so that does indeed appear to be the issue. Thank you!

**Comment by aheber** [comment] 2024-07-08 14:17
I've added a ticket to get it added to the docs. Hopefully the next person to run into it will be able to get an easier answer.
