### ISSUE TITLE
Apex Trigger has not been deployed error (potential Winter 24 issue)

### ISSUE THREAD

**Issue by tehnrd** [SFDO-Community/declarative-lookup-rollup-summaries#1383] opened 2023-08-29 15:29 UTC
**Describe the bug**
In a Winter 24 sandbox I am unable to save or run Full Calculate on any previously created Rollup Summaries.

**To Reproduce**
Run an a Full Calculate on an existing Rollup Summary in a Winter 24 sandbox. Or attempt to create a new Rollup Summary and set Active to true.

**Expected behavior**
Records should be saveable and runable.

**Screenshots**
<img width="1678" alt="Screenshot 2023-08-29 at 11 17 53 AM" src="https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/assets/1007085/507011aa-e817-4d2a-a5d6-e9c44aa82b40">

**Comment by dacmanj** [comment] 2023-08-29 15:44
I'm also seeing this after the update to Winter 24. None of our lookups will save through the manage wizard/button and frontend.

**Comment by aheber** [comment] 2023-08-29 18:00
I'm able to reproduce in a sandbox on Winter '24.

I'll be able to test more tomorrow and will see if I can figure out what is going on. I'll report back.

**Comment by tehnrd** [comment] 2023-08-29 19:32
Thanks @aheber. Not sure if you do hot fixes for this package, but this might be worthy of one. Winter 24 is not in prod yet but this issue is preventing the creation of new and running existing Rollups in sandboxes.

**Comment by TravisHendrix-HendrixSD** [comment] 2023-08-29 19:53
I am having the exact same issue in any org that has been updated to Winter 24.

**Comment by aheber** [comment] 2023-08-29 19:59
I'll know more later. If this is an intentional change by the platform then we'll address it quickly. If Winter '24 is broken and will be fixed then we likely won't do anything because Salesforce will need to fix it.

Depending on the nature and intention of the change we might need to determine the right action, it might be a loss of functionality if we can't look for installed Apex anymore. At least a loss of the ability to validate that the trigger of expected name is installed.

**Comment by aheber** [comment] 2023-08-29 21:10
I've been able to isolate this to what I think is happening. Looks like WHERE clauses using the Name field of ApexTrigger aren't finding the associated records, looking like the Trigger isn't installed now.
I've opened a support case with Salesforce to investigate. My guess is this is a bug in Winter '24 that needs to be fixed and not something DLRS will be able to fix in our code. I'm having the same problem outside of the package and namespace. 
Running `SELECT Id, Name FROM ApexTrigger WHERE Name = 'EXPECTED_NAME'` returns zero results, even using my admin user. I expect this isn't intentional.


I'll keep this issue updated as I get news.

**Closed** 2023-08-31 16:25 UTC
Labels: bug

**Comment by tehnrd** [comment] 2023-08-31 17:54
Thanks for the update, glad SF will fix this.

FWIW, our sandbox is on Winter '24 Patch 4.1  but still seeing the issue. Will continue to monitor.

**Comment by aheber** [comment] 2023-08-31 21:57
Hmmm. I guess it isn't an official patch yet, maybe just testing the fix on my pod for now?

Please keep me updated so I can have some idea when it is officially rolling out.
Thanks!

**Comment by aheber** [comment] 2023-09-01 21:32
https://issues.salesforce.com/issue/a028c00000uXYtiAAG

**Comment by brandonpitts3** [comment] 2023-09-13 17:07
I can confirm that the workaround mentioned by @peterdesio also worked for us.

**Comment by abdul0503** [comment] 2023-09-15 08:44
Hello @aheber, I am facing the same issue and raised a ticket with salesforce, can you please share with me the ticket number which you have raised to resolve this issue?

**Comment by aheber** [comment] 2023-09-15 15:50
@abdul0503 the known issue generated by my ticket is https://issues.salesforce.com/issue/a028c00000uXYtiAAG, if you're experiencing issues you should be able to follow up on that.
My originating case was #45231051, they built and tested a patch in the org hosting my sandbox and confirmed they knew how to fix it with an expectation that over time they would roll that fix out to all Winter '24 sandboxes. I don't know if that has happened but fully expect that the production release will include this fix.

For those that were able to remove and recreate then things worked, this matches the testing that Salesforce did. Only Triggers that went through the upgrade process were un-findable but anything added later appeared to work correctly.

**Comment by abdul0503** [comment] 2023-09-18 10:43
thank you @aheber
