### ISSUE TITLE
dlrs_CaseTrigger: execution of AfterUpdate caused by: System.DmlException: Upsert failed. First exception on row 0; first error: DUPLICATE_VALUE, duplicate value found: dlrs__QualifiedParentID__c duplicates value on record with id: a6L3n000000NPlY: [] (dlrs)

### ISSUE THREAD

**Issue by paartho** [SFDO-Community/declarative-lookup-rollup-summaries#1039] opened 2021-06-07 20:34 UTC
I am getting this error while creating a case by clicking over a Global Action at Salesforce community.

dlrs_CaseTrigger: execution of AfterUpdate caused by: System.DmlException: Upsert failed. First exception on row 0; first error: DUPLICATE_VALUE, duplicate value found: dlrs__QualifiedParentID__c duplicates value on record with id: a6L3n000000NPlY: [] (dlrs)

I have updated to 2.13(Latest Version), but doesn't helped me to solve the issue. 

Thanks in advance for any help

**Comment by aheber** [comment] 2023-03-15 20:03
We have some previous reports of this happening for Guest Users, do you think this is a similar problem?

I know if you search the previous issues there is a variety of solutions but I don't think there is an officially accepted recommendation at this time.

I believe this is a duplicate of the previous issues and I'll mark it closed. If you think this situation is different just chime back in and let us know.

**Closed by aheber** 2023-03-15 20:03 UTC
Labels: Support Team
