### ISSUE TITLE
Getting this Error ID: 41155647-144471 (-1547370483)

### ISSUE THREAD

**Issue by JM05122021** [SFDO-Community/declarative-lookup-rollup-summaries#1035] opened 2021-05-12 20:44 UTC
**IMPORTANT NOTE** The Chatter Community Group can be found [here](https://success.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F9300000009O5p). If it is an issue that you need help on configuring the tool or have an unexpected error its really worth seeing if the community can help first before raising a GitHub issue. Most users hangout in the Chatter Community Group. Otherwise if prefer you can post here and still link in the Chatter Community Group.
Salesforce support asked me to reach out to group to see you could help track down the source of this error message.  Here is the full message

Review the errors on this page.
dlrs_RecallTrigger: execution of AfterInsert caused by: System.DmlException: Update failed. First exception on row 0 with id (I removed the accountID); first error: CANNOT_EXECUTE_FLOW_TRIGGER, We can't save this record because the “Account - Create or Edit” process failed. Give your Salesforce admin these details. This error occurred when the flow tried to update records: FIELD_CUSTOM_VALIDATION_EXCEPTION: Move the Case to Preliminary Close before moving to Closed.. You can look up ExceptionCode values in the SOAP API Developer Guide.---This error occurred when the flow tried to update records: FIELD_CUSTOM_VALIDATION_EXCEPTION: Move the Case to Preliminary Close before moving to Closed.. You can look up ExceptionCode values in the SOAP API Developer Guide. Error ID: 41155647-144471 (-1547370483): [] Class.dlrs.RollupService.Updater.updateRecords: line 1381, column 1 Class.dlrs.RollupService.UpdateWithoutSharing.updateRecords: line 1424, column 1 Class.dlrs.RollupService.updateRecords: line 1352, column 1 Class.dlrs.RollupService.handleRollups: line 1000, column 1 Class.dlrs.RollupService.triggerHandler: line 311, column 1 Trigger.dlrs_RecallTrigger: line 7, column 1

**Comment by aheber** [comment] 2023-03-15 19:55
@JM05122021 this error is likely coming from a DLRS rollup that is trying to rollup to a parent record. This is a custom validation rule that ensures (probably) Case record needs to move to Preliminary Close prior to be being moved to Closed. That doesn't mean anything to me but I'm guessing you have a 'prior status' field on Case that is being checked in the validation rule. 

This is an issue with that particular record's ability to be updated compliant with your systems rules/validations. DLRS is exposing that record's problems but isn't likely the root cause of the problem.

If you find that you need further support we'd request you to work with the Trailblazer Community Group for DLRS which is where most of our experts hang out and and can provide support.

Hope that helps if this is still an issue.

**Closed by aheber** 2023-03-15 19:55 UTC
Labels: Support Team
