### ISSUE TITLE
Rounding Off Issue

### ISSUE THREAD

**Issue by vinodhranganathan** [SFDO-Community/declarative-lookup-rollup-summaries#859] opened 2019-08-30 10:26 UTC
When rolling up currency field from child records to parent (using DLRS) there is difference of few pennies. 

Example
--------------
Child Records (FinServ__AssetsAndLiabilities__c)
------------------------------------------------------
1) GBP 300,000.00 
2) GBP 300,000.00

Rolled Up Value On Parent Record (Account)
-------------------------------------------------

GBP 599,999.99

I have checked the value in developer console. It is GBP 300,000.00 on the child records. This issue is happening only when rolling up to one specific Account record.

**Comment by harrisoe69** [comment] 2019-09-11 12:58
We've noticed this issue as well. Our workaround to create a formula field and convert the currency to a number then use that field as a source to aggregate.

**Comment by afawcett** [comment] 2019-12-28 02:35
Thanks for sharing @harrisoe69, thats a really good workaround! @vinodhranganathan hope this helped! cc @JimBTek fyi

**Comment by afawcett** [comment] 2019-12-28 02:36
Going to flag this as a source for a wiki page about curreny issues.

**Comment by vinodhranganathan** [comment] 2020-01-09 15:59
Thanks harrisoe69. We have enabled multi currency in our org. So if there are two child records with different currencies, will rolling up these values to parent record (with different currency) work properly with integer type formula field?

**Example**

**Child Records (FinServ__AssetsAndLiabilities__c)**
USD 300,000.00
GBP 300,000.00

**Rolled Up Value On Parent Record (Account)**
SGD 939,518.00

**Comment by aheber** [comment] 2023-03-18 18:49
Duplicate of #284 
Some good details here though.

**Closed by aheber** 2023-03-18 18:49 UTC
Labels: Documentation Team
