### ISSUE TITLE
Bug - Msg states child trigger needs to be deployed but it already has; unable to edit roll-up as result

### ISSUE THREAD

**Issue by baobao917** [SFDO-Community/declarative-lookup-rollup-summaries#1385] opened 2023-09-05 15:57 UTC
**Describe the bug**
On all the roll-ups, it indicates that the child trigger needs to be deployed but it already has.  Even if trying to re-deploy the trigger...once complete, conflicting messaging is displayed indicating:

-- Deployment complete.
-- Click Deploy to install the Apex Trigger and Apex Class for this child object.

**To Reproduce**
See demo video - https://www.loom.com/share/c81aa3426c574d89b113f33610f56ae5?sid=71e55c85-d5b3-4347-b524-28bfa50d01c2

**Expected behavior**
Trigger deployed and the ability to edit the roll-up

**Screenshots**
![image](https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/assets/104730171/805c16de-ceca-484a-8361-4ab64e8060fd)

![image](https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/assets/104730171/6f415397-b223-4c8d-83a8-e43a5ed610cc)

![image](https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/assets/104730171/8a6dce53-8c96-49ec-9c5b-890c4348b925)

![image](https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/assets/104730171/8a2dd4ec-d264-4f0f-8f2d-4025207e43c9)

**Additional context**
N/A

**Comment by aheber** [comment] 2023-09-05 21:48
@baobao917, thank you for a great review and detailed notes. This appears to be a duplicate of #1383. Salesforce has a Known Issues with the Winter '24 release and is expected to rollout a patch to all orgs shortly.

If you believe your situation isn't a duplicate please reopen and help me understand. Thanks!

**Closed by aheber** 2023-09-05 21:48 UTC
Labels: bug
