### ISSUE TITLE
Value '0' is updated on Parent Record even when no child record is present. My child record is a feedback object.Due to this even if client has not filled the feedback it appears client has rated with 0 feedback.Any help regarding this will be appreciated 

### ISSUE THREAD

**Issue by nkulkarni2021** [SFDO-Community/declarative-lookup-rollup-summaries#804] opened 2019-03-20 07:20 UTC

**Comment by JimBTek** [comment] 2019-05-10 14:34
Have you tried using a query filter to ignore records with blank fields?

**Comment by afawcett** [comment] 2019-12-28 06:19
Hmmm i think this has been raised before, sometimes folks want it to be null, othertimes zero when their is no aggregate result. I am sure we have an enhancement to add a option to control this behavior but will flag this one for now as an enhancement and do a de-dupe later.

**Comment by aheber** [comment] 2021-10-09 16:53
Duplicate of #161, we invite you to review the notes there and provide any input/additional criteria to help us reach an action plan.

**Closed by aheber** 2021-10-09 16:53 UTC
Labels: enhancement
