### ISSUE TITLE
Apex error DUPLICATE_VALUE, duplicate value found: dlrs__UniqueName__c 

### ISSUE THREAD

**Issue by climenhaga** [SFDO-Community/declarative-lookup-rollup-summaries#956] opened 2020-06-23 17:56 UTC
I have created multiple DLRS that are scheduled and have been working fine for several weeks but  just got an Apex error related to a DLRS:

Apex script unhandled trigger exception by user/organization: 005f4000000SSyf/00Df4000000m7L4
dlrs_TaskTrigger: execution of AfterInsert caused by: System.DmlException: Insert failed. First exception on row 0; first error: DUPLICATE_VALUE, duplicate value found: dlrs__UniqueName__c duplicates value on record with id: a2Rf4000001TMBA: []Class.dlrs.RollupService.updateMasterRollupsTrigger: line 1012, column 1
Class.dlrs.RollupService.handleRollups: line 919, column 1
Class.dlrs.RollupService.triggerHandler: line 311, column 1
Trigger.dlrs_TaskTrigger: line 7, column 1

The user referenced is a Portal Guest User.

The record with the duplicate UniqueName is a dlrs__LookupRollupSummary__c

I see this record shows it was created by an end user. I see that the configurations I have made are stored as MetaData and the Portal Guest User did not have permission to the dlrs.Lookup Rollup Summary Custom MetaData. It also doesn't have permissions to any of the DLRS Custom Objects. 

The DLRS that caused the error Sums a field on Task and puts the result on Contact. I can't find any automation where a task could be created by Portal Guest User but it could update a contact.

I'm not sure how to reproduce this.

**Comment by afawcett** [comment] 2020-07-21 03:17
@climenhaga this looks like an issue fixed in the latest release - please review the release notes carefully. Let me know if this does not help.

**Comment by mizzltoy** [comment] 2020-07-21 16:55
@climenhaga - we were having this same issue with records being created by the guest user.  We had to the give the guest user profile "read" access to the DLRS objects in order to resolve the issue.

**Comment by aheber** [comment] 2024-05-26 22:45
Duplicate of #375

**Closed by aheber** 2024-05-26 22:45 UTC
Labels: discussion
