### ISSUE TITLE
Install Fails due to encrypted fields in subscriber org

### ISSUE THREAD

**Issue by erinjane80** [SFDO-Community/declarative-lookup-rollup-summaries#1068] opened 2021-09-15 09:34 UTC
Package: Declarative Lookup Rollup Summaries Tool (04t5p000000eegF) Error Number: 1855348825-63467 (1328681604)
Problem:

1.  Name = :testRecordName order by Name
                                ^
ERROR at Row:1:Column:111
field 'Name' can not be sorted in a query call
fflib_SObjectUnitOfWorkTest: 
Name = :testRecordName order by Name
                                ^
ERROR at Row:1:Column:111
field 'Name' can not be sorted in a query call

2.  OpportunityLineItems) from Opportunity where Name like 'UoW Test Name %' order
                                             ^ ERROR at Row:1:Column:79 The operator like is not supported on an encrypted field
fflib_SObjectUnitOfWorkTest: 
OpportunityLineItems) from Opportunity where Name like 'UoW Test Name %' order
                                             ^ ERROR at Row:1:Column:79 The operator like is not supported on an encrypted field

3.  PricebookEntry.Product2.Name) from Opportunity where Name like 'UoW Test Name %' order
                                                     ^ ERROR at Row:1:Column:169 The operator like is not supported on an encrypted field
fflib_SObjectUnitOfWorkTest: 
PricebookEntry.Product2.Name) from Opportunity where Name like 'UoW Test Name %' order
                                                     ^ ERROR at Row:1:Column:169 The operator like is not supported on an encrypted field

4.  PricebookEntry.Product2.Name) from Opportunity where Name like 'UoW Test Name %' order
                                                     ^ ERROR at Row:1:Column:157 The operator like is not supported on an encrypted field
fflib_SObjectUnitOfWorkTest: 
PricebookEntry.Product2.Name) from Opportunity where Name like 'UoW Test Name %' order
                                                     ^ ERROR at Row:1:Column:157 The operator like is not supported on an encrypted field

5.  OpportunityLineItems) from Opportunity where Name like :filter order by Name
                                             ^ ERROR at Row:1:Column:79 The operator like is not supported on an encrypted field
fflib_SObjectUnitOfWorkTest: 
OpportunityLineItems) from Opportunity where Name like :filter order by Name
                                             ^ ERROR at Row:1:Column:79 The operator like is not supported on an encrypted field

I've had no problems installing on a scratch org, but in my partial-copy sandbox I get these errors.
When I turn off encryption on the Opportunity Name, I'm able to install. However, once the package is installed, I am no longer able to turn encrpytion back on on the Opportunity Name.

**Comment by Szandor72** [comment] 2021-09-15 10:52
Hello erinjane80,

it seems the org you want to install to has field encryption enabled. 

DLRS doesn't support encrypted fields currently. Thanks for bringing this to our attention - we need to discuss internally.

**Comment by quintencls** [comment] 2022-05-12 09:25
@Szandor72 @erinjane80  We are experiencing the same issue on Contact Name. Do you know if anything happened in relation to encryption support the past year? Thanks a lot!

**Comment by aheber** [comment] 2023-05-05 02:27
@quintencls,  I don't think the class you mentioned, `ConvertRecordsToCSVQueueableTest`,  is a DLRS class. I suspect this is other Apex installed in your environment.

I'm going to close this as a duplicate of #865

**Closed** 2023-05-05 02:27 UTC
Labels: enhancement, Dev Team
