### ISSUE TITLE
Guest user changes break DLRS Scheduled rollups

### ISSUE THREAD

**Issue by gbutt** [SFDO-Community/declarative-lookup-rollup-summaries#987] opened 2020-10-05 14:32 UTC
**Describe the bug**
In winter 21 Salesforce is enforcing guest user restrictions in all orgs. These restrictions include:
1. Guest user cannot own records
2. Guest user can only obtain read access to records via Sharing Settings

It is this second setting that causes issues for rollups in Scheduled mode. This causes an insurmountable issue for DLRS rollups in Scheduled mode. Scheduled mode will insert or update in the Scheduled Items object. This object has a unique key based on Parent ID and CMDT ID. If the guest user triggers a Scheduled rollup, and a Scheduled Item does not exist, then the guest user is able to create a Scheduled Item without issue. If the guest user triggers a Scheduled rollup, and a Scheduled Item does exist, then an error is thrown when the guest user attempts to update that Scheduled Item.

**To Reproduce**
I have created [this SFDX repo](https://github.com/gbutt/dlrs-scheduled-guest-issue) to reproduce this error
1. Install DLRS version 2.12
2. Create a form where a guest user can insert contacts under a known account
3. Create a Scheduled rollup with Contact as child and Account as parent - [screenshot of rollup config](https://raw.githubusercontent.com/gbutt/dlrs-scheduled-guest-issue/main/dlrs-job-config.png)
4. Using the guest user, create two contacts

**Expected behavior**
Both contacts are created without error.

**Actual behavior**
The second contact results in an error because the guest user cannot update the Scheduled Item created with the first contact.

**Additional context**
The only way I know to fix this issue is to change the code to execute without sharing.

**Comment by drewpiston** [comment] 2021-03-05 17:47
Just wanted to chime in and say this is still an issue and affecting many of my clients. 

The only workarounds I know of right now are:
- change the rollup to be realtime (or full recalc every night)
- have the guest site user insert data into an intermediate "holding" object and then use a scheduled flow (or other process) to create a Contact based on that intermediate object

**Comment by ritturoy** [comment] 2021-03-09 23:27
We face the same issue

**Comment by swift-ben** [comment] 2021-04-06 14:03
We're also running into this with our clients and it's a pretty big issue as we have a lot of clients that use Sites to collect data. Any input or advice would be greatly appreciated.

**Comment by evaLordNJII** [comment] 2022-07-13 03:36
I am receiving the error message, "insufficient access on cross reference entity" and I am not a guest user, I am the System Administrator.   Can anyone advise on how I can resolve this issue.  The assistance is greatly appreciated

**Comment by streetyouth** [comment] 2022-08-13 20:26
I believe I am experiencing this now on code that has been running for years using V4SF (Volutneers for Salesfroce) and DLRS together to help keep things straight. It is my understanding that this is because some child records that the guest site (V4SF) user are updating are in scheduled mode (incremental) and that the only workable solutions right now are to change the scheduled (incremental implied) to scheduled full or realtime.

**Comment by streetyouth** [comment] 2022-08-14 01:11
This problem first manifest as "duplicate parents" error and then when I added read-only permission as "inadequate access / Read only access" error. Fixed by changing to real-time mode.

**Comment by aheber** [comment] 2024-05-26 22:45
Duplicate of #375

**Closed by aheber** 2024-05-26 22:45 UTC
Labels: bug
