### ISSUE TITLE
Unable to uninstall

### ISSUE THREAD

**Issue by Stubedo** [SFDO-Community/declarative-lookup-rollup-summaries#770] opened 2018-12-10 17:51 UTC
Unable to uninstall:

Apex Class | RollupService | Component is in use by another component in your organization. dlrs_Sales_InvoiceTrigger

**Comment by aheber** [comment] 2018-12-10 18:56
Ideally, you can navigate to the rollup that installed that Trigger, use the Manage Trigger button and uninstall the trigger.

If you no longer have that rollup you'll either need to go down to the developer layer and execute a destructive change to remove the trigger or, probably easier, create a new rollup on the Sales_Invoice__c object and use Manage Trigger to remove the trigger from there.

Let us know if you need additional instructions or help.

**Comment by afawcett** [comment] 2019-12-28 05:48
We could really do with an unstall wiki page. Also a utility to remove triggers without having to re-create the rollup definition.

**Comment by aheber** [comment] 2023-03-18 18:30
Duplicate of #674

**Closed by aheber** 2023-03-18 18:30 UTC
Labels: duplicate, enhancement, Documentation Team
