### ISSUE TITLE
CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, dlrs_ContactTrigger: execution of AfterUpdate caused by: System.SObjectException: Invalid field Account for Contact (dlrs): []

### ISSUE THREAD

**Issue by amatigianc** [SFDO-Community/declarative-lookup-rollup-summaries#1044] opened 2021-07-01 15:04 UTC
**Describe the bug**
Salesforce Classic
Declarative Lookup rollup version 2.13
When a rep tries to close an opportunity which also contains a contact role we get this error message:

pex trigger Opportunity_OutComeTask caused an unexpected exception, contact your administrator: Opportunity_OutComeTask: execution of AfterUpdate caused by: System.DmlException: Update failed. First exception on row 0 with id 0036f00003QOGM9AAP; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, dlrs_ContactTrigger: execution of AfterUpdate caused by: System.SObjectException: Invalid field Account for Contact (dlrs): []: ()

Also attaching screenshot of my job configuration.
![Screenshot 2021-07-01 at 16 00 51](https://user-images.githubusercontent.com/7075253/124146330-9299f180-da85-11eb-9003-93c814eb5f43.png)

Same error message applied when converting a lead to a contact. The same error applies when trying to save a case record

![LeadConvertError](https://user-images.githubusercontent.com/7075253/124146176-6d0ce800-da85-11eb-8e59-ba0444ec2970.png)

**To Reproduce**
1. Create an opportunity
2. Add one contact role
3. Make sure the job similar to mine is active

**Expected behavior**
This error should just not happen. 

**Screenshots**
 attached
![LeadConvertError](https://user-images.githubusercontent.com/7075253/124146660-e4db1280-da85-11eb-9057-e1d8efe2dc54.png)

**Additional context**

**Comment by cmurph09** [comment] 2022-05-13 19:08
Experiencing the exact same issue for a Case trigger. Seems to be happening only when cases are merged. Is there any update on this issue? The error message doesn't give any guidance to where to go to fix.

**Comment by ReginaHodge** [comment] 2022-08-11 17:07
Hi, has this been addressed? I'm getting a similar error ("dlrs_ContactTrigger: execution of AfterUpdate caused by: System.SObjectException: Invalid field Account for Contact (dlrs)") when an integration tries to create a new contact record. In my case NPSP is creating a household account for the contact.

**Closed** 2023-03-15 20:19 UTC
Labels: bug, Support Team
