### ISSUE TITLE
Enhancement: set a default value on Aggregate Result Field when null result

### ISSUE THREAD

**Issue by dwindibank** [SFDO-Community/declarative-lookup-rollup-summaries#702] opened 2018-06-07 14:47 UTC
When none of the child objects meet the Relationship Criteria we would like to be able to set the Aggregate Result Field to a default value rather than null. 

We use a large number of DLRS rollups and we've had to create several processes that just look for null values in fields and set them back to the default values, it would amazing if it could be handled as part of the definition of the DLRS. 

An example use case: rolling up the status on a contact from active opportunities (first sorted by value), but setting the status back to the default value once there are no active opportunities.

**Comment by aheber** [comment] 2023-03-14 03:31
Grouping as a duplicate of #161 to pull these together as a single request.

**Closed by aheber** 2023-03-14 03:31 UTC
Labels: enhancement, Dans List
