### ISSUE TITLE
Ability to Bulk Remove Child Triggers (was Uninstall without Child Triggers)

### ISSUE THREAD

**Issue by marioessig** [SFDO-Community/declarative-lookup-rollup-summaries#602] opened 2017-12-19 21:35 UTC
I have deleted all the Lookup Rollup Summaries without reading any instructions beforehand. Now I am unable to look for the triggers and remove Child Triggers. 

How can I uninstall DLRS now?

The error shows:
![screen shot 2017-12-19 at 3 34 37 pm](https://user-images.githubusercontent.com/33463458/34179858-261724a8-e4d2-11e7-84a9-54804f1c5776.png)

![screen shot 2017-12-19 at 3 35 00 pm](https://user-images.githubusercontent.com/33463458/34179871-34216798-e4d2-11e7-84f3-c925bc4cfbce.png)

**Comment by aheber** [comment] 2017-12-19 21:40
There are complicated ways to remove classes from a production Salesforce instance. 

Most certainly your best bet is to quickly rebuild rollups on the same child objects and use the expected flow for uninstall via the Manage Child Trigger button.

If you like pain and suffering you can explore this option instead:
http://www.simplysfdc.com/2016/12/salesforce-delete-trigger-and-apex.html
(These are some of the more concise instructions I found)

**Comment by afawcett** [comment] 2018-01-01 02:52
Its possible to add an uninstall page and provide a means to bulk undeploy the triggers. I'll flag this as an enhancement.

**Comment by aheber** [comment] 2023-03-09 05:57
Calling this a duplicate of #674 as this would be part of the Trigger Management page.

**Closed by aheber** 2023-03-09 05:57 UTC
Labels: enhancement
